#!/bin/bash

  $* 2>&1 | tee mailpro_out_"$$".txt

  { echo "Command:"
    echo "$*"
    echo "Tail of Output:"
    tail mailpro_out_"$$".txt
    } | \
    mail -s $MAILPRO_SUBJECT \
    $MAILPRO_ADDRESS

  rm mailpro_out_*.txt

exit

