#!/bin/bash

  $* 2>&1 | tee mailpro_out_"$$"

  source $HOME/.mailpro_profile

  { echo "Command:"
    echo "$*"
    echo "Output:"
    tail mailpro_out_"$$"
    } | \
    mail -s $MAILPRO_SUBJECT \
    $MAILPRO_ADDRESS

  rm mailpro_out_"$$"

# Uncomment the following code for a more robust mailpro_out_PID clean function. (In case something unexpected happens while doing "rm mailpro_out_'$$'".)

#   if [ -f mailpro_out_* ];
#     then
#     for file_name in [$(ls mailpro_out_*)]:
#     do
#       IFS='_' read -ra ADDR <<< file_name
#       if [! kill -0 ${ADDR[2]}];
#         then rm file_name
#       fi
#     done
#   fi

exit 0

